### PR TITLE
Formatting for Careers Page

### PR DESCRIPTION
**Pull request by bitbrewer**
Add scala, akka, and play icons.

Not ready yet.

### CODE REVIEW

**Comment by benash** [comment]
Are we using Play?

**Comment by benash** [comment]
Also, can we just add the SVGs to this repo as separate files?

**Comment by bitbrewer** [comment]
We can move the SVGs. They are embedded in the markdown for now. Let's merge this and then I'll create a new PR for that change.

**Comment by bitbrewer** [comment]
We've used Play for some sample apps in the past.

**Comment by benash** [comment]
👍

**Pull request merged**
